stage 'Build'
node {
    git url: 'ssh://git@gitlab/acme-insurance/insurancepolicy.git', branch: "${branch}", credentialsId: 'jenkins'
    def version = getBuildVersion("pom.xml")
    env.BUILD_VERSION = version
    env.BUILD_GROUP_ID = getGroupIdFromPom("pom.xml")
    env.BUILD_ARTIFACT_ID = getArtifactIdFromPom("policyquote/pom.xml")
    def branch = 'build-' + version
    env.BUILD_BRANCH = branch
    prepareBuild(version, branch)
    build()
    stash excludes: 'target/', includes: '**', name: 'source'
}

stage 'Integrate'
node {
    unstash 'source'
    integrationTests()    
}

stage 'Publish'
node {
    unstash 'source'
    publishToNexusAndCommitBranch(env.BUILD_VERSION, env.BUILD_BRANCH)
}

stage 'QA'
node {
    deployToBPMS("bpmsqa:8080")
}

//release build
if ("${branch}".startsWith("release")) { 
  stage 'Approve'
  timeout(time: 2, unit: 'DAYS') {
    input message: 'Does the release build look ok?'
  }
}

//production build
if ("${branch}".startsWith("master")) { 
  stage 'Approve'
  timeout(time: 2, unit: 'DAYS') {
    input message: 'Do you want to deploy into production?'
  }

  stage 'Production'
  node {
    deployToBPMS("bpmsprod:8080")
  }
}

def prepareBuild(version, branch) {
    sh "git checkout -b ${branch}"
    withEnv(["PATH+MAVEN=${tool 'maven-3.2.5'}/bin"]) {
        sh "mvn -f pom.xml versions:set -DgenerateBackupPoms=false -DnewVersion=${version}"
    }
}

def build() {	
    withEnv(["PATH+MAVEN=${tool 'maven-3.2.5'}/bin"]) {
        sh "mvn -f pom.xml clean package"
    }
}

def integrationTests() {
    withEnv(["PATH+MAVEN=${tool 'maven-3.2.5'}/bin"]) {	
	    sh "mvn -f pom.xml verify"
    }
}

def publishToNexusAndCommitBranch(version, branch) {
    withEnv(["PATH+MAVEN=${tool 'maven-3.2.5'}/bin"]) {
        sh "mvn -f pom.xml deploy -DaltDeploymentRepository=internal.nexus::default::http://nexus:8080/nexus/content/repositories/releases"
        def commit = "Build " + version
        sh "git add pom.xml **/pom.xml && git commit -m \"${commit}\" && git push origin ${branch}"
    }
}

def deployToBPMS(server) {
    def payload = new StringBuilder()
                        .append("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>")
                        .append("<kie-container container-id=\"policyquote-")
                        .append(env.BUILD_VERSION)
                        .append("\">")
                        .append("<release-id>")
                        .append("<group-id>")
                        .append(env.BUILD_GROUP_ID)
                        .append("</group-id>")
                        .append("<artifact-id>")
                        .append(env.BUILD_ARTIFACT_ID)
                        .append("</artifact-id>")
                        .append("<version>")
                        .append(env.BUILD_VERSION)
                        .append("</version>")
                        .append("</release-id></kie-container>")
                        .toString()

    sh "curl -X PUT -H 'Content-Type: application/xml' -d '${payload}' http://admin1:admin@${server}/kie-server/services/rest/server/containers/policyquote-${env.BUILD_VERSION}"
}


def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
 }

def getGroupIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
  matcher ? matcher[0][1] : null
 }

def getArtifactIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
  matcher ? matcher[0][1] : null
 }

def String getBuildVersion(pom) {
  def version = getVersionFromPom(pom);
  if (version.contains("SNAPSHOT")) {
    return version.minus("-SNAPSHOT") + '.' + env.BUILD_NUMBER
  } else {
    return version + '.' + env.BUILD_NUMBER
  }
}
